# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
zh:
  languageCode: zh-Hans
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  # contentDir: content/zh  # omit contentDir if translating by file name.
  title: 可视化作品集 by Oxford Roadmapping
  weight: 1

# Uncomment the lines below to configure your website in a second language.
en:
  languageCode: en
  # contentDir: content/en  # omit contentDir if translating by file name.
  title: Visualization by Oxford Roadmapping
  weight: 2      
  params:
    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
en:
  languageCode: zh-Hant
  # contentDir: content/zht  # # omit contentDir if translating by file name.
  title: 可视化作品集 by Oxford Roadmapping
  weight: 3
  params:
    description: Site description in Chinese...
