# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language

### https://github.com/gohugoio/locales/blob/master/zh_Hant/zh_Hant.go
### https://github.com/gohugoio/locales/blob/master/zh_Hans/zh_Hans.go

zh:
  languageCode: zh
  # contentDir: content/zh  # omit contentDir if translating by file name.
  title: 可视化 及 AI 智能体 作品集 by 牛津路线图 Oxford Roadmapping
  weight: 1
  params:
    description: 本站汇集从科研影响力到净零路线的可视化 及 AI Agent (AI 智能体) 作品, 展示牛津路线图做战略洞察的实证依据。
    formats:
      date:
        long: 2006 2月28日 周日
        medium: 2006 2月28日
        short: 2006/02/28
      time:
        long: 3:04:05 下午
        medium: 3:04 下午
        short: 3:04 PM
      datetime:
        long: 2006 2月28日 周日 3:04:05 下午
        medium: 2006 2月28日 3:04 下午
        short: 2006/02/28 3:04 PM    
en:
  languageCode: en
  # contentDir: content/en  # omit contentDir if translating by file name.
  title: Visualization by Oxford Roadmapping
  weight: 5      
  params:
    description: Ranging form Science Impact to Net Zero, this site cureates the visualization works by Oxford Roadmapping for strategic foresight.
    formats:
      date:
        long: Monday, 2 January, 2006
        medium: 2 January, 2006
        short: 2006-01-02
      time:
        long: 3:04:05 PM
        medium: 3:04 PM
        short: 3:04PM
      datetime:
        long: Monday, 2 January, 2006 3:04:05 PM
        medium: 2 January, 2006 3:04 PM
        short: 2006-01-02 3:04PM
zh-Hant:
  # contentDir: content/zht  # # omit contentDir if translating by file name.
  # https://discourse.gohugo.io/t/localizing-date-format/37868 The comparison is case-insensitive. You may use underscores or hyphens.
  languageCode: zh-Hant
  languageName: 正體中文
  title: 可視化 及 AI Agent 作品集 by 牛津路線圖 Oxford Roadmapping
  weight: 3
  params:
    description: 本站彙整從科研影響力到淨零路線的 可視化 及 AI Agent (AI 代理) 作品, 展示牛津路線圖做戰略洞察的實依據
    formats:
      date:
        long: 2006 2月28 周日
        medium: 2006 2月28
        short: 2006/02/28
      time:
        long: 3:04:05 下午
        medium: 3:04 下午
        short: 3:04 PM
      datetime:
        long: 2006 2月28 周日 3:04:05 下午
        medium: 2006 2月28 3:04 下午
        short: 2006/02/28 3:04 PM    
