# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: 科研评估🎯
    url: 'portfolio'
    weight: 10
  - name: 图富明察💹
    url: 'intro'
    weight: 20
  - name: 连络📪
    url: '#contact'
    weight: 60
